// import "tailwindcss/tailwind.css";
import Head from "next/head";
import "../styles.css";
function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>PairHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
